In [1]:
import numpy as np
import pandas as pd

In [3]:
result=[]
test_dict1={
    "name":"czw",
    "age":18
}
test_dict2={
    "name":"star",
    "age":20,
    "sex":"male"
}
result.append(test_dict1)
result.append(test_dict2)
pd.DataFrame(result)

   name  age   sex
0   czw   18   NaN
1  star   20  male

In [4]:
test_jitfine=pd.read_pickle("features_test.pkl")
test_cct5=pd.read_pickle("features_test_fixed.pkl")

In [5]:
test_jitfine

,project,parent_hashes,commit_hash,author_name,author_email,author_date,author_date_unix_timestamp,commit_message,la,ld,...,ndev,lt,nuc,age,exp,rexp,sexp,classification,fix,is_buggy_commit
0,ant-ivy,b1cfd88a8c23302077bda847f4da7f0b5fc59ec1,6e710a1f78a4a733020a4b2d1f07b6fe4c6684f0,Maarten Coene,maartenc@apache.org,Tue Sep 2 20:13:38 2008 +0000,1220386418,FIX : Invalid URL when using dynamic ranges ( ...,31,0,...,4,70.0,13,7.928263888888889,227.0,123.5498262760538,192.0,Corrective,True,1.0
1,ant-ivy,2e5e29dd504694426fee6138bf37c38e7510c56f,1f73722ffb375010e74eaa5b99004ad88df93bf6,Xavier Hanin,xavier@apache.org,Wed Sep 3 07:52:46 2008 +0000,1220428366,IMPROVEMENT : Parse license information in pom...,49,4,...,4,348.5,102,33.86203125,819.0,354.63383025409223,572.0,None,False,1.0
2,ant-ivy,72ff5791d73055e23e0d81979a07079e81774b23,cfa7c5e3bba0efbc88dfb2fcafb983723a1606bc,Xavier Hanin,xavier@apache.org,Wed Sep 3 08:19:46 2008 +0000,1220429986,"IMPROVEMENT : write home page , description an...",51,1,...,4,140.0,30,178.60596643518517,820.0,355.6243727522805,573.0,None,False,1.0
3,ant-ivy,4cd2d2256ae019fa32705e865ae2e95623ec35cc,951b253fc38c09114d0fe273a3758a15c151a8b4,Maarten Coene,maartenc@apache.org,Sat Sep 6 20:32:48 2008 +0000,1220733168,FIX : Ivy ibiblio resolver chokes on variables...,28,30,...,4,320.6666666666667,94,3.5278009259259258,231.0,126.69710233263446,153.0,Corrective,True,1.0
4,ant-ivy,cc73787eca843c7cef7882c4efaf9ec27350029a,48055baa938695fa302fc8aa51a5a2df24c73fe7,Xavier Hanin,xavier@apache.org,Mon Sep 15 09:17:13 2008 +0000,1221470233,fix style,76,58,...,4,102.81818181818181,150,20.20576494107744,824.0,353.62356378666703,748.0,Corrective,True,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5475,gora,c64f4a533a44a7a947f14e225c8ddeffe3962095,9b4f29d41a71f58e2a0a31d03f1bb8117a9e8d60,madhawa-gunasekara,madhawa30@gmail.com,Sun Mar 24 19:53:51 2019 +0530,1553437431,GORA - 545 Fix split size in infinispan store,1,5,...,19,343.0,6,306.4168055555556,20.0,8.086322441968052,0.0,Corrective,True,0.0
5476,gora,b4b0228125aa129ca84efeea63b9c7dac9b61cb3,2325c61a9280d310818f99dea19853718c613557,Kevin Ratnasekera,djkevincr@yahoo.com,Sun Mar 31 23:31:23 2019 +0530,1554055283,Improve Flink module with custom serializer,255,44,...,19,146.45454545454547,62,316.449929503367,34.0,16.541432958832065,6.666666666666667,None,False,0.0
5477,gora,c4e29f3e7d2823406a8d675c376935bbf03396d4,e6e6c2d91e0e8b6549b5eda8973e5f3c150a7774,Kevin Ratnasekera,djkevincr@yahoo.com,Mon Apr 1 00:39:09 2019 +0530,1554059349,Fix HBase Store Flink,5,0,...,12,-6.0,6,1317.1925,35.0,17.539877987503143,2.0,Corrective,True,0.0
5478,gora,8bb377b272666c2e9d071293f5416c95ffae0a01,ab40eadf2da890903f4c5d74d0cb6f5459a5f995,Kevin Ratnasekera,djkevincr@yahoo.com,Wed Apr 3 00:24:48 2019 +0530,1554231288,GORA - 549 : Remove PersistentBase extending j...,1,1,...,19,-60.0,36,2.0370949074074076,37.0,19.46521817135962,19.0,None,False,0.0
5479,gora,8bb377b272666c2e9d071293f5416c95ffae0a01,7b80edbfe28a488e1bbbe69741ff9f8432a676b8,sc306,Sheriffo Ceesay,Sat Apr 6 23:21:26 2019 +0100,1554589286,Remove deprecated API calls from HbaseStore an...,5,3,...,21,785.5,96,26.68476273148148,0.0,0.0,0.0,None,False,0.0

In [5]:
test_cct5.columns

Index(['project', 'parent_hashes', 'commit_hash', 'author_name',
       'author_email', 'author_date', 'author_date_unix_timestamp',
       'commit_message', 'la', 'ld', 'fileschanged', 'nf', 'ns', 'nd',
       'entropy', 'ndev', 'lt', 'nuc', 'age', 'exp', 'rexp', 'sexp',
       'classification', 'fix', 'is_buggy_commit'],
      dtype='object')